name: Output from a cond step

on:
  workflow_dispatch:
    inputs:
      skip:
        type: boolean
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "value=test" >> $GITHUB_OUTPUT
        if: inputs.skip
        id: sut
      - run: |
          echo "we ran"
          echo value was ${{ steps.sut.outputs.value }}
        if: steps.sut.outputs.value == 'test'
      - run: |
          echo "we didnt ran"
          echo value was ${{ steps.sut.outputs.value }}
        if: steps.sut.outputs.value != 'test'
