name: Play around with expressions

on:
  workflow_call:
    inputs:
      value:
        required: true
        type: boolean
        default: false

jobs:
  expression:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ fromJSON('["first", "second"]')[1] }}
