name: Play around with expressions

on:
  workflow_call:
    inputs:
      value:
        required: true
        type: boolean
        default: false

jobs:
  expression:
    runs-on: ubuntu-latest
    steps:
    - id: var
      if: inputs.value
      run: echo "result=hello" >> GITHUB_OUTPUT
    - run: write-output $var
      shell: bash
    - run: echo ${{ steps.var.outputs.result }}
