name: push-commit
on:
  workflow_dispatch:
jobs:
  push:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - name: Create changelog for overmind
        shell: powershell
        run: |
          If (!(git tag -l "latest")) {
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag latest
          git push origin latest
          }
          git log latest.. --format="%s | %an %ar%n" --output="${{ runner.temp }}/Development/Games/${Env:ShortProductName}/CHANGELOG.txt"
